require 'hdf5';
require 'image';
require 'nn';
net = torch.load('./VGG_FACE.t7')
net:evaluate()
print(net)
local layers = hdf5.open('./network.h5', 'w')
layers:write('1', net.modules[1].weight)
layers:write('3', net.modules[3].weight)
layers:write('6', net.modules[6].weight)
layers:write('8', net.modules[8].weight)
layers:write('11', net.modules[11].weight)
layers:write('13', net.modules[13].weight)
layers:write('15', net.modules[15].weight)
layers:write('18', net.modules[18].weight)
layers:write('20', net.modules[20].weight)
layers:write('22', net.modules[22].weight)
layers:write('25', net.modules[25].weight)
layers:write('27', net.modules[27].weight)
layers:write('29', net.modules[29].weight)
layers:write('33', net.modules[33].weight)
layers:write('36', net.modules[36].weight)
layers:write('39', net.modules[39].weight)
layers:write('1b', net.modules[1].bias)
layers:write('3b', net.modules[3].bias)
layers:write('6b', net.modules[6].bias)
layers:write('8b', net.modules[8].bias)
layers:write('11b', net.modules[11].bias)
layers:write('13b', net.modules[13].bias)
layers:write('15b', net.modules[15].bias)
layers:write('18b', net.modules[18].bias)
layers:write('20b', net.modules[20].bias)
layers:write('22b', net.modules[22].bias)
layers:write('25b', net.modules[25].bias)
layers:write('27b', net.modules[27].bias)
layers:write('29b', net.modules[29].bias)
layers:write('33b', net.modules[33].bias)
layers:write('36b', net.modules[36].bias)
layers:write('39b', net.modules[39].bias)
layers:close()
